#!/usr/bin/env bash
# Shared helpers sourced by the script/* commands. Not executable on its own.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---------------------------------------------------------------------------
# Project configuration. These are the only values tied to a specific
# project — edit them (or override in .env) when reusing these scripts for
# another exported Lovable/Supabase project.
# ---------------------------------------------------------------------------
PROJECT_ID="team-jeopardy"                    # local stack namespace; must match supabase/config.toml
PROD_PROJECT_REF="uwcmnaswnlxyxytxlntr"       # hosted Supabase project ref
PROD_REGION="us-east-1"                       # hosted project region (for pooler hosts)
PROD_URL="https://${PROD_PROJECT_REF}.supabase.co"

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

require_tools() {
  command -v docker >/dev/null 2>&1 || die "Docker is required. Install Docker Desktop: https://docs.docker.com/desktop/"
  docker info >/dev/null 2>&1 || die "The Docker daemon is not running. Start Docker Desktop and retry."
  docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (ships with Docker Desktop)."
  command -v supabase >/dev/null 2>&1 || die "The Supabase CLI is required. Install: brew install supabase/tap/supabase"
}

# Load secrets/config from the git-ignored root .env, if present.
# Values in .env override the defaults above.
load_env() {
  if [ -f .env ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
  fi
}

# Regenerate supabase/functions/.env (what the local Edge Runtime reads)
# from the root .env, so there is a single place to configure secrets.
sync_function_env() {
  {
    echo "# GENERATED by script/* from the root .env — edit .env instead."
    echo "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
  } >supabase/functions/.env
}

supabase_running() { supabase status >/dev/null 2>&1; }

start_supabase() {
  if supabase_running; then return 0; fi
  local other
  other="$(docker ps --format '{{.Names}}' | grep '^supabase_db_' || true)"
  [ -n "$other" ] && warn "another local Supabase stack is running ($other); if start fails on a port conflict, stop it first"
  info "Starting local Supabase stack (first run downloads Docker images; this can take a few minutes)"
  supabase start
}

# Resolve the Postgres container of OUR stack. Tries the CLI project label
# first, then falls back to the conventional name.
db_container() {
  local c
  c="$(docker ps --filter "label=com.supabase.cli.project=$PROJECT_ID" --format '{{.Names}}' | grep '^supabase_db_' | head -1 || true)"
  [ -z "$c" ] && c="$(docker ps --format '{{.Names}}' | grep -x "supabase_db_$PROJECT_ID" || true)"
  [ -n "$c" ] || die "cannot find the Supabase Postgres container — is the stack running? (supabase status)"
  echo "$c"
}

dpsql() { # run psql inside the Supabase db container
  docker exec -i "$(db_container)" psql -U postgres -d postgres -v ON_ERROR_STOP=1 "$@"
}

# Prints the number of games, or dies if the database is unreachable.
games_count() {
  local n
  n="$(dpsql -tAc 'select count(*) from public.games')" || die "could not query public.games — try script/reset"
  echo "$n"
}

# Empty every application table (schema stays intact).
truncate_all_data() {
  dpsql -q <<'SQL'
do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' loop
    execute format('truncate table public.%I restart identity cascade', r.tablename);
  end loop;
end $$;
SQL
}

# True if a restorable data snapshot exists in db/.
snapshot_available() { [ -f db/data.dump ] || [ -f db/data.sql ]; }

# Restore the point-in-time data snapshot from db/.
# Prefers db/data.dump (pg_dump custom format, written by
# script/download-supabase-database-dump); falls back to db/data.sql.
restore_snapshot() {
  if [ -f db/data.dump ]; then
    info "Restoring snapshot from db/data.dump (pg_restore)"
    truncate_all_data
    docker exec -i "$(db_container)" pg_restore -U postgres -d postgres --data-only --no-owner --disable-triggers <db/data.dump
  elif [ -f db/data.sql ]; then
    info "Restoring snapshot from db/data.sql (psql)"
    truncate_all_data
    dpsql -q <db/data.sql
  else
    die "no snapshot found (expected db/data.dump or db/data.sql) — run script/download-supabase-database-dump first, or script/bootstrap --empty"
  fi
  info "Snapshot restored: $(games_count) games"
}

verify_schema() {
  local ok
  ok="$(dpsql -tAc "select to_regclass('public.games') is not null and exists (select 1 from pg_proc where proname = 'generate_unique_slug')")"
  [ "$ok" = "t" ] || die "schema verification failed: public.games or generate_unique_slug missing. Try script/reset."
  info "Schema verified (public.games + functions present)"
}
